package com.trivi.model;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;

@DynamoDBTable(tableName = "game")
public class Game {

    private String  id;
    private Long startTime;
    private Long endTime;
    private List<Player> players;
    private GameAnswers gameAnswers;
    private List<Question> questionBank;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    @DynamoDBAttribute
    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }
    @DynamoDBAttribute
    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }
    @DynamoDBAttribute
    public List<Player> getPlayers() {
        return players;
    }

    public void setPlayers(List<Player> players) {
        this.players = players;
    }
    @DynamoDBAttribute
    public GameAnswers getGameAnswers() {
        return gameAnswers;
    }

    public void setGameAnswers(GameAnswers gameAnswers) {
        this.gameAnswers = gameAnswers;
    }
    @DynamoDBAttribute
    public List<Question> getQuestionBank() {
        return questionBank;
    }

    public void setQuestionBank(List<Question> questionBank) {
        this.questionBank = questionBank;
    }
}
